// Portraits from Wikimedia Commons, each with its author and licence so the
// credits on /methodik are exact. Served directly, no runtime lookup. People
// without a freely licensed photo keep the monogram avatar.
export type Portrait = { name: string; src: string; author: string; license: string; page: string };

export const PORTRAITS: Record<string, Portrait> = {
  "Warren_Buffett": { name: "Warren Buffett", src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d4/Warren_Buffett_at_the_2015_SelectUSA_Investment_Summit_%28cropped%29.jpg/330px-Warren_Buffett_at_the_2015_SelectUSA_Investment_Summit_%28cropped%29.jpg", author: "USA International Trade Administration", license: "Public domain", page: "https://commons.wikimedia.org/wiki/File:Warren_Buffett_at_the_2015_SelectUSA_Investment_Summit_(cropped).jpg" },
  "Bill_Ackman": { name: "Bill Ackman", src: "https://upload.wikimedia.org/wikipedia/commons/0/07/Valeant_Pharmaceuticals%27_Business_Model_%28headshot%29.jpg", author: "Senate Democrats", license: "CC BY 2.0", page: "https://commons.wikimedia.org/wiki/File:Valeant_Pharmaceuticals%27_Business_Model_(headshot).jpg" },
  "George_Soros": { name: "George Soros", src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/97/George_Soros%2C_Founder_and_Chairman_of_the_Open_Society_Foundations%2C_visits_the_EC_%283x4_cropped%29.jpg/330px-George_Soros%2C_Founder_and_Chairman_of_the_Open_Society_Foundations%2C_visits_the_EC_%283x4_cropped%29.jpg", author: "Aris Oikonomou / European Commission", license: "CC BY 4.0", page: "https://commons.wikimedia.org/wiki/File:George_Soros,_Founder_and_Chairman_of_the_Open_Society_Foundations,_visits_the_EC_(3x4_cropped).jpg" },
  "Charlie_Munger": { name: "Charlie Munger", src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/56/Charlie_Munger_%28cropped%29.jpg/330px-Charlie_Munger_%28cropped%29.jpg", author: "Nick", license: "CC BY 2.0", page: "https://commons.wikimedia.org/wiki/File:Charlie_Munger_(cropped).jpg" },
  "Ray_Dalio": { name: "Ray Dalio", src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1f/Web_Summit_2018_-_Forum_-_Day_2%2C_November_7_HM1_7481_%2844858045925%29.jpg/330px-Web_Summit_2018_-_Forum_-_Day_2%2C_November_7_HM1_7481_%2844858045925%29.jpg", author: "Web Summit", license: "CC BY 2.0", page: "https://commons.wikimedia.org/wiki/File:Web_Summit_2018_-_Forum_-_Day_2,_November_7_HM1_7481_(44858045925).jpg" },
  "Steven_A._Cohen": { name: "Steven A. Cohen", src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ab/Steve_baseball_4_%281%29_%28cropped%29.jpg/330px-Steve_baseball_4_%281%29_%28cropped%29.jpg", author: "Michael Seib", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Steve_baseball_4_(1)_(cropped).jpg" },
  "Seth_Klarman": { name: "Seth Klarman", src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b8/Seth_Klarman_at_147th_Preakness_Stakes.jpg/330px-Seth_Klarman_at_147th_Preakness_Stakes.jpg", author: "Maryland GovPics", license: "CC BY 2.0", page: "https://commons.wikimedia.org/wiki/File:Seth_Klarman_at_147th_Preakness_Stakes.jpg" },
  "Nancy_Pelosi": { name: "Nancy Pelosi", src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a5/Official_photo_of_Speaker_Nancy_Pelosi_in_2019.jpg/330px-Official_photo_of_Speaker_Nancy_Pelosi_in_2019.jpg", author: "John Harrington", license: "Public domain", page: "https://commons.wikimedia.org/wiki/File:Official_photo_of_Speaker_Nancy_Pelosi_in_2019.jpg" },
  "Mohnish_Pabrai": { name: "Mohnish Pabrai", src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0d/Mohnish_Pabrai.jpg/330px-Mohnish_Pabrai.jpg", author: "Fabarsi", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Mohnish_Pabrai.jpg" },
};
