"""Generate lib/wordmark.ts: the ĀURA wordmark as one SVG path.

Letters come from Inter Tight (scripts/fonts, OFL) at a fixed weight with wide
tracking; the bar over the first A is drawn at stem weight across the A's full
width, a little above the cap height.

    pip install fonttools brotli
    python3 scripts/generate-wordmark.py            # from web/
"""

from __future__ import annotations

import re
from pathlib import Path

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

WEB = Path(__file__).resolve().parents[1]
FONT = WEB / "scripts/fonts/InterTight-latin.woff2"
OUT = WEB / "lib/wordmark.ts"
WEIGHT = 620
TRACKING = 0.14  # em between letters
BAR_GAP = 0.13  # em between cap height and bar
SCALE = 0.05  # font units -> path units


def main() -> None:
    font = instantiateVariableFont(TTFont(FONT), {"wght": WEIGHT})
    upm = font["head"].unitsPerEm
    glyphs = font.getGlyphSet()
    cmap = font.getBestCmap()

    paths, boxes, x = [], [], 0.0
    for i, ch in enumerate("AURA"):
        name = cmap[ord(ch)]
        pen = SVGPathPen(glyphs)
        glyphs[name].draw(TransformPen(pen, (1, 0, 0, -1, x, 0)))
        paths.append(pen.getCommands())
        bounds = BoundsPen(glyphs)
        glyphs[name].draw(bounds)
        boxes.append((x, bounds.bounds))
        x += font["hmtx"][name][0] + (TRACKING * upm if i < 3 else 0)

    ax, (a0, _, a1, a_top) = boxes[0]
    thick = upm * (0.056 + (WEIGHT - 400) / 400 * 0.04)
    top = -a_top - BAR_GAP * upm - thick
    paths.insert(0, f"M{ax + a0:.1f} {top:.1f}H{ax + a1:.1f}V{top + thick:.1f}H{ax + a0:.1f}Z")

    x0 = min(bx + b[0] for bx, b in boxes)
    x1 = max(bx + b[2] for bx, b in boxes)
    y0, y1 = top, max(-b[1] for _, b in boxes)

    def scale(cmd: str) -> str:
        out, op, n = [], "", 0
        for tok in re.findall(r"[A-Za-z]|-?\d+(?:\.\d+)?", cmd):
            if tok.isalpha():
                op, n = tok, 0
                out.append(tok)
                continue
            v = float(tok)
            if op in "MLCQ":
                v = (v - x0) * SCALE if n % 2 == 0 else (v - y0) * SCALE
            elif op == "H":
                v = (v - x0) * SCALE
            elif op == "V":
                v = (v - y0) * SCALE
            n += 1
            out.append(f"{v:.1f}".rstrip("0").rstrip(".").replace("-0", "0") if abs(v) < 0.05 else f"{v:.1f}".rstrip("0").rstrip("."))
        return re.sub(r" ?([A-Za-z]) ?", r"\1", " ".join(out))

    d = "".join(scale(p) for p in paths)
    OUT.write_text(
        "// ĀURA wordmark: Inter Tight (OFL) at weight 620 with 0.14 em tracking, as\n"
        "// one path so it renders identically everywhere. The bar over the first A is\n"
        "// drawn at stem weight across the A's full width. Generated by\n"
        "// scripts/generate-wordmark.py; edit the generator, not the numbers.\n"
        f"export const WORDMARK_WIDTH = {round((x1 - x0) * SCALE, 1)};\n"
        f"export const WORDMARK_HEIGHT = {round((y1 - y0) * SCALE, 1)};\n"
        "export const WORDMARK_PATH =\n"
        f'  "{d}";\n'
    )
    print(f"wrote {OUT.relative_to(WEB)}")


if __name__ == "__main__":
    main()
