"""Generate lib/wordmark.ts: the ĀURA wordmark as one SVG path.

Letters come from Inter Tight (scripts/fonts, OFL) at a fixed weight with wide
tracking. The first A loses its crossbar and gets a bar above instead (the
same Ā as the welcome screen and the app icon): drawn at stem weight across
the A's full width, a little above the cap height.

    pip install fonttools brotli
    python3 scripts/generate-wordmark.py            # from web/
"""

from __future__ import annotations

import re
from pathlib import Path

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

WEB = Path(__file__).resolve().parents[1]
FONT = WEB / "scripts/fonts/InterTight-latin.woff2"
OUT = WEB / "lib/wordmark.ts"
WEIGHT = 620
TRACKING = 0.14  # em between letters
BAR_GAP = 0.13  # em between cap height and bar
SCALE = 0.05  # font units -> path units


def main() -> None:
    font = instantiateVariableFont(TTFont(FONT), {"wght": WEIGHT})
    upm = font["head"].unitsPerEm
    glyphs = font.getGlyphSet()
    cmap = font.getBestCmap()

    paths, boxes, x = [], [], 0.0
    for i, ch in enumerate("AURA"):
        name = cmap[ord(ch)]
        pen = SVGPathPen(glyphs)
        glyphs[name].draw(TransformPen(pen, (1, 0, 0, -1, x, 0)))
        cmds = pen.getCommands()
        if i == 0:
            # Inter Tight draws the A as a Λ plus a separate crossbar
            # rectangle (M H V H Z); the mark keeps only the Λ.
            contours = ["M" + c for c in cmds.split("M") if c]
            bars = [c for c in contours if re.fullmatch(r"M[-\d. ]+H[-\d.]+V[-\d.]+H[-\d.]+Z", c)]
            assert len(bars) == 1, contours
            cmds = "".join(c for c in contours if c not in bars)
        paths.append(cmds)
        bounds = BoundsPen(glyphs)
        glyphs[name].draw(bounds)
        boxes.append((x, bounds.bounds))
        x += font["hmtx"][name][0] + (TRACKING * upm if i < 3 else 0)

    ax, (a0, _, a1, a_top) = boxes[0]
    thick = upm * (0.056 + (WEIGHT - 400) / 400 * 0.04)
    top = -a_top - BAR_GAP * upm - thick
    paths.insert(0, f"M{ax + a0:.1f} {top:.1f}H{ax + a1:.1f}V{top + thick:.1f}H{ax + a0:.1f}Z")

    x0 = min(bx + b[0] for bx, b in boxes)
    x1 = max(bx + b[2] for bx, b in boxes)
    y0, y1 = top, max(-b[1] for _, b in boxes)

    def scale(cmd: str) -> str:
        out, op, n = [], "", 0
        for tok in re.findall(r"[A-Za-z]|-?\d+(?:\.\d+)?", cmd):
            if tok.isalpha():
                op, n = tok, 0
                out.append(tok)
                continue
            v = float(tok)
            if op in "MLCQ":
                v = (v - x0) * SCALE if n % 2 == 0 else (v - y0) * SCALE
            elif op == "H":
                v = (v - x0) * SCALE
            elif op == "V":
                v = (v - y0) * SCALE
            n += 1
            out.append(f"{v:.1f}".rstrip("0").rstrip(".").replace("-0", "0") if abs(v) < 0.05 else f"{v:.1f}".rstrip("0").rstrip("."))
        return re.sub(r" ?([A-Za-z]) ?", r"\1", " ".join(out))

    d = "".join(scale(p) for p in paths)
    # The Ā alone (bar + Λ): welcome screen, app icons.
    mark = "".join(scale(p) for p in paths[:2])
    mark_w = round((boxes[0][1][2] - boxes[0][1][0]) * SCALE, 1)
    mark_h = round((-boxes[0][1][1] - y0) * SCALE, 1)
    OUT.write_text(
        "// ĀURA wordmark: Inter Tight (OFL) at weight 620 with 0.14 em tracking, as\n"
        "// one path so it renders identically everywhere. The first A has no\n"
        "// crossbar; its bar sits above it at stem weight across the full width (the\n"
        "// mark of the welcome screen and app icon). Generated by\n"
        "// scripts/generate-wordmark.py; edit the generator, not the numbers.\n"
        f"export const WORDMARK_WIDTH = {round((x1 - x0) * SCALE, 1)};\n"
        f"export const WORDMARK_HEIGHT = {round((y1 - y0) * SCALE, 1)};\n"
        "export const WORDMARK_PATH =\n"
        f'  "{d}";\n'
        "\n"
        "// The Ā on its own, same units (welcome screen, app icons).\n"
        f"export const MARK_WIDTH = {mark_w};\n"
        f"export const MARK_HEIGHT = {mark_h};\n"
        f'export const MARK_PATH = "{mark}";\n'
    )
    print(f"wrote {OUT.relative_to(WEB)}")


if __name__ == "__main__":
    main()
